export const courseCategories = [
    { value: "technology", label: "Technology" },
    { value: "business", label: "Business" },
    { value: "arts", label: "Arts" },
    { value: "science", label: "Science" },
    { value: "health", label: "Health" },
    { value: "marketing", label: "Marketing" },
    { value: "finance", label: "Finance" },
    { value: "photography", label: "Photography" },
    { value: "personal-development", label: "Personal Development" },
    { value: "languages", label: "Languages" },
    { value: "music", label: "Music" },
    { value: "data-science", label: "Data Science" },
    { value: "software-development", label: "Software Development" },
    { value: "machine-learning", label: "Machine Learning" },
    { value: "ai", label: "Artificial Intelligence" },
    { value: "cloud-computing", label: "Cloud Computing" },
    { value: "cybersecurity", label: "Cybersecurity" },
    { value: "networking", label: "Networking" },
    { value: "blockchain", label: "Blockchain" },
    { value: "game-development", label: "Game Development" },
    { value: "design", label: "Design" },
    { value: "graphic-design", label: "Graphic Design" },
    { value: "ui-ux", label: "UI/UX Design" },
    { value: "web-development", label: "Web Development" },
    { value: "mobile-development", label: "Mobile Development" },
    { value: "video-editing", label: "Video Editing" },
    { value: "writing", label: "Writing" },
    { value: "creative-writing", label: "Creative Writing" },
    { value: "journalism", label: "Journalism" },
    { value: "psychology", label: "Psychology" },
    { value: "nutrition", label: "Nutrition" },
    { value: "sports", label: "Sports" },
    { value: "fitness", label: "Fitness" },
    { value: "yoga", label: "Yoga" },
    { value: "meditation", label: "Meditation" },
    { value: "cooking", label: "Cooking" },
    { value: "baking", label: "Baking" },
    { value: "gardening", label: "Gardening" },
    { value: "education", label: "Education" },
    { value: "teaching", label: "Teaching" },
    { value: "test-prep", label: "Test Preparation" },
    { value: "entrepreneurship", label: "Entrepreneurship" },
    { value: "real-estate", label: "Real Estate" },
    { value: "law", label: "Law" },
    { value: "history", label: "History" },
    { value: "economics", label: "Economics" },
    { value: "philosophy", label: "Philosophy" },
    { value: "biology", label: "Biology" },
    { value: "chemistry", label: "Chemistry" },
    { value: "physics", label: "Physics" },
    { value: "environment", label: "Environmental Science" },
  ];