export const courseCategories = [
  { value: "technology", label: "Technology" },
  { value: "business", label: "Business" },
  { value: "arts", label: "Arts" },
  { value: "science", label: "Science" },
  { value: "health", label: "Health" },
  { value: "marketing", label: "Marketing" },
  { value: "finance", label: "Finance" },
  { value: "photography", label: "Photography" },
  { value: "personal-development", label: "Personal Development" },
  { value: "languages", label: "Languages" },
  { value: "music", label: "Music" },
  { value: "data-science", label: "Data Science" },
  { value: "software-development", label: "Software Development" },
  { value: "machine-learning", label: "Machine Learning" },
  { value: "ai", label: "Artificial Intelligence" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "networking", label: "Networking" },
  { value: "blockchain", label: "Blockchain" },
  { value: "game-development", label: "Game Development" },
  { value: "design", label: "Design" },
  { value: "graphic-design", label: "Graphic Design" },
  { value: "ui-ux", label: "UI/UX Design" },
  { value: "web-development", label: "Web Development" },
  { value: "mobile-development", label: "Mobile Development" },
  { value: "video-editing", label: "Video Editing" },
  { value: "writing", label: "Writing" },
  { value: "creative-writing", label: "Creative Writing" },
  { value: "journalism", label: "Journalism" },
  { value: "psychology", label: "Psychology" },
  { value: "nutrition", label: "Nutrition" },
  { value: "sports", label: "Sports" },
  { value: "fitness", label: "Fitness" },
  { value: "yoga", label: "Yoga" },
  { value: "meditation", label: "Meditation" },
  { value: "cooking", label: "Cooking" },
  { value: "baking", label: "Baking" },
  { value: "gardening", label: "Gardening" },
  { value: "education", label: "Education" },
  { value: "teaching", label: "Teaching" },
  { value: "test-prep", label: "Test Preparation" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "real-estate", label: "Real Estate" },
  { value: "law", label: "Law" },
  { value: "history", label: "History" },
  { value: "economics", label: "Economics" },
  { value: "philosophy", label: "Philosophy" },
  { value: "biology", label: "Biology" },
  { value: "chemistry", label: "Chemistry" },
  { value: "physics", label: "Physics" },
  { value: "environment", label: "Environmental Science" },
];

export const courseLanguages = [
  { value: "english", label: "English" },
  { value: "hindi", label: "Hindi" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "chinese", label: "Chinese" },
  { value: "marathi", label: "Marathi" },
  { value: "other", label: "Other" },
];

export const badgeObjects = [
  {
    id: 1,
    name: "Pirate Captain",
    imagePath: "/TMA-badges/TMAbadge-1.jpeg",
    unlocked: false,
    condition: " Collect 200 coins and complete 5 lessons",
    coins: 200,
    lessons: 5,
    quizzes: 0,
  },
  {
    id: 2,
    name: "Treasure Hunter",
    imagePath: "/TMA-badges/TMAbadge-2.jpeg",
    unlocked: false,
    condition: "Collect 500 coins, complete 5 lessons, and finish 10 quizzes.",
    coins: 500,
    lessons: 5,
    quizzes: 10,
  },
  {
    id: 3,
    name: "Sea Navigator",
    imagePath: "/TMA-badges/TMAbadge-3.jpeg",
    unlocked: false,
    condition: "Collect 1,000 coins, complete 15 lessons, and finish 20 quizzes.",
    coins: 1000,
    lessons: 15,
    quizzes: 20,
  },
  {
    id: 4,
    name: "Ghost Ship",
    imagePath: "/TMA-badges/TMAbadge-4.jpeg",
    unlocked: false,
    condition: "Collect 2,500 coins and complete 20 lessons.",
    coins: 2500,
    lessons: 20,
    quizzes: 0,
  },
  {
    id: 5,
    name: "Legendary Sword",
    imagePath: "/TMA-badges/TMAbadge-5.jpeg",
    unlocked: false,
    condition: "Finish 30 quizzes and collect 3,000 coins.",
    coins: 3000,
    lessons: 0,
    quizzes: 30,
  },
  {
    id: 6,
    name: "Kraken Slayer",
    imagePath: "/TMA-badges/TMAbadge-6.jpeg",
    unlocked: false,
    condition: "Complete 25 lessons and finish 40 quizzes.",
    coins: 0,
    lessons: 25,
    quizzes: 40,
  },
  {
    id: 7,
    name: "Gold Hoarder",
    imagePath: "/TMA-badges/TMAbadge-7.jpeg",
    unlocked: false,
    condition: "Collect 5,000 coins, complete 30 lessons, and finish 45 quizzes.",
    coins: 5000,
    lessons: 30,
    quizzes: 45,
  },
  {
    id: 8,
    name: "Master Gunner",
    imagePath: "/TMA-badges/TMAbadge-8.jpeg",
    unlocked: false,
    condition: "Complete 40 lessons and collect 7,500 coins.",
    coins: 7500,
    lessons: 40,
    quizzes: 0,
  },
  {
    id: 9,
    name: "Crew Leader",
    imagePath: "/TMA-badges/TMAbadge-9.jpeg",
    unlocked: false,
    condition: "Finish 60 quizzes and collect 10,000 coins",
    coins: 10000,
    lessons: 0,
    quizzes: 60,
  },
  {
    id: 10,
    name: "Island Explorer",
    imagePath: "/TMA-badges/TMAbadge-10.jpeg",
    unlocked: false,
    condition: "Complete 50 lessons, finish 80 quizzes, and collect 15,000 coins.",
    coins: 15000,
    lessons: 50,
    quizzes: 80,
  },
  {
    id: 11,
    name: "Legendary Captain",
    imagePath: "/TMA-badges/TMAbadge-11.jpeg",
    unlocked: false,
    condition: "Earn 20,000 coins, complete 60 lessons, and finish 120 quizzes.",
    coins: 20000,
    lessons: 60,
    quizzes: 120,
  },
  {
    id: 12,
    name: "Davy Jones' Nemesis",
    imagePath: "/TMA-badges/TMAbadge-12.jpeg",
    unlocked: false,
    condition: "Earn 50,000 coins, complete 100 lessons, and finish 175 quizzes.",
    coins: 50000,
    lessons: 100,
    quizzes: 175,
  },
]