import { Geist, Geist_Mono } from "next/font/google";
import 'video.js/dist/video-js.css'; // Ensure Video.js styles are included
import './globals.css'; // Reference your custom global styles
import '@fortawesome/fontawesome-free/css/all.min.css'; // Import Font Awesome styles

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

